# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CSVExportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 229)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 190, 281, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 281, 171))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_axis_06 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_axis_06.setChecked(True)
        self.checkBox_axis_06.setObjectName("checkBox_axis_06")
        self.gridLayout.addWidget(self.checkBox_axis_06, 2, 1, 1, 1)
        self.checkBox_axis_01 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_axis_01.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_axis_01.setChecked(True)
        self.checkBox_axis_01.setObjectName("checkBox_axis_01")
        self.gridLayout.addWidget(self.checkBox_axis_01, 0, 0, 1, 1)
        self.checkBox_axis_04 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_axis_04.setObjectName("checkBox_axis_04")
        self.gridLayout.addWidget(self.checkBox_axis_04, 0, 1, 1, 1)
        self.checkBox_axis_03 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_axis_03.setObjectName("checkBox_axis_03")
        self.gridLayout.addWidget(self.checkBox_axis_03, 2, 0, 1, 1)
        self.checkBox_axis_02 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_axis_02.setObjectName("checkBox_axis_02")
        self.gridLayout.addWidget(self.checkBox_axis_02, 1, 0, 1, 1)
        self.checkBox_axis_05 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_axis_05.setObjectName("checkBox_axis_05")
        self.gridLayout.addWidget(self.checkBox_axis_05, 1, 1, 1, 1)
        self.checkBox_axis_07 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_axis_07.setObjectName("checkBox_axis_07")
        self.gridLayout.addWidget(self.checkBox_axis_07, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CSV Export"))
        self.groupBox.setTitle(_translate("Dialog", "Select Axis"))
        self.checkBox_axis_06.setText(_translate("Dialog", "Axis Spannung"))
        self.checkBox_axis_01.setText(_translate("Dialog", "Axis Soll"))
        self.checkBox_axis_04.setText(_translate("Dialog", "Axis Beschl. aus Geschw."))
        self.checkBox_axis_03.setText(_translate("Dialog", "Axis Weg"))
        self.checkBox_axis_02.setText(_translate("Dialog", "Axis Geschwindigkeit"))
        self.checkBox_axis_05.setText(_translate("Dialog", "Axis Beschl. aus Geschw. (Filter)"))
        self.checkBox_axis_07.setText(_translate("Dialog", "Axis Beschl. aus Weg"))
