# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1392, 808)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 129, 1401, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mplLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mplLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mplLayout.setContentsMargins(0, 0, 0, 0)
        self.mplLayout.setObjectName("mplLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 161, 81))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 141, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_btn_grp_01 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_btn_grp_01.setContentsMargins(0, 0, 0, 0)
        self.layout_btn_grp_01.setObjectName("layout_btn_grp_01")
        self.btn_load = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_load.setObjectName("btn_load")
        self.layout_btn_grp_01.addWidget(self.btn_load)
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_save.setObjectName("btn_save")
        self.layout_btn_grp_01.addWidget(self.btn_save)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 10, 271, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_compare = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_compare.setObjectName("btn_compare")
        self.gridLayout.addWidget(self.btn_compare, 0, 0, 1, 1)
        self.combo_viewmode_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_viewmode_2.setObjectName("combo_viewmode_2")
        self.combo_viewmode_2.addItem("")
        self.combo_viewmode_2.addItem("")
        self.combo_viewmode_2.addItem("")
        self.gridLayout.addWidget(self.combo_viewmode_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1392, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered['bool'].connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "CSV"))
        self.btn_load.setText(_translate("MainWindow", "Laden"))
        self.btn_save.setText(_translate("MainWindow", "Speichern"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Auswerten"))
        self.btn_compare.setText(_translate("MainWindow", "Verleiche Soll-Ist"))
        self.combo_viewmode_2.setItemText(0, _translate("MainWindow", "Überlappend"))
        self.combo_viewmode_2.setItemText(1, _translate("MainWindow", "Untereinander"))
        self.combo_viewmode_2.setItemText(2, _translate("MainWindow", "Nebeneinander"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
